name: wm01-tiger
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10.4
  - snakemake=7.8.2
  # # libpython and m2w64-toolchain install a c++ compiler for pymc3-theano.
  # # However, these packages are only available on Windows.
  # # - libpython=2.1
  # # - m2w64-toolchain=5.3.0
  - notebook=6.4.12
  - nbgrader=0.7.0
  - sqlalchemy=1.4.37
  - jinja2=3.1.2
  - nbconvert=6.5.0
  - jupyterhub=2.3.1
  - numpy=1.22.4
  - matplotlib=3.5.1
  - pandas=1.4.2
  - scipy=1.8.1
  - seaborn=0.11.2
  - imageio=2.9.0
  - imageio-ffmpeg=0.4.7
  - scikit-image=0.19.2
  - scikit-learn=1.1.1
  - python-graphviz=0.20
  - nose=1.3.7
  - pip=22.1.2
  - biopython=1.79
  - requests=2.28.0
  - pyyaml=6.0
  - scikit-learn-extra=0.2.0
  - sympy=1.10.1
  - pytables=3.7.0
  - panel=0.13.0
  - hvplot=0.7.3
  - pip:
      - adskalman==0.3.11
      - pymc==4.0.0
      - dabest==0.3.1
      - figurefirst==0.0.6
